- name: Install neovim
  homebrew: name=neovim

- pip:
    name: neovim
    executable: pip3
    state: forcereinstall

- name: Create a config directory
  file:
    path: ~/.config/nvim/
    state: directory

- name: Create a symlink for the vim config
  file:
    src: "{{ playbook_dir }}/../configs/init.vim"
    path: ~/.config/nvim/init.vim
    state: link
    force: true

- name: Create a directory for plugins
  file:
    path: ~/.config/nvim/autoload/
    state: directory

- name: Install vim-plug
  get_url:
    dest: ~/.config/nvim/autoload/plug.vim
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
